language: node_js
sudo: false
node_js:
- 7.7.3
addons:
  sauce_connect: true
env:
  global:
  - TZ=America/Los Angeles
  - SAUCE_USERNAME=penguinstampede
  - secure: oXJFgEa3/RA19ZvYNXKIod0fLSe+ue6uxPhEg+DqlvV0+91QXfuK+yus0B0vqITUlJGNn5sq9rkDEeDF7cu32ctSQSXNEtUFnOxXe8zs9Alob7Ej/PS9qSpnR8zTryOE0Fn+ow4/a02KphaTFPsCMaGi47ZsQjeaZwogQ7MorwXnZQu1mVj306rks9DSl40T4FcvhQfT+YH2WZQlhgTUKdnbmr81lEOgI3nPBLjrlAzsL2fBX8zIK48DDi39VHi5n1IOnz/c5WkBtdycqLJz1Muz5yiPOboVdld1umfBriuUYDEuVTkdCvXmAbMFEnYAf619psuE0HpZBjAPAvuzxfGNSC/bK8e86SQglR3j0K7sgA22QcyhJgQR/WgL0izyRVmWmVgsVCxmMKOPaY7iYwnm42RvgtUUwrTdIfGOyx2DRUWgWVvUXEqNRuosiW5RGUHfRadBSxQVVlsUtNdxTjqFCxg76KgrrX49bZe86eov2Y5BYOqGCmVQEnAz9RpYdWmV0Img4VaX5NkhXCD4NAbo//y/3dwtszQFS580w8MK1P6YYcl72N9VaJghyC0i1YpW7SFnzUyc5+nXpZ9oQxqjakBp30C7iwf1midVu8dOhtE3pdk8xoz9A5j+zZ0QFK+00Cfx9b2X2p3i6pDzsA9i3wy6kkUEy7JCvOFzaRE=
  - secure: JRbrWZpDEkgG1rJC8x9a/YQTtC4RoFsr6P05puCCwIO7WolyfI48RGgKg4N2auOrJzfIWP4zSnAaqHv5TclbVJciDBLqAXOuqcoi9LEabUJHEqQfYF4Aec5SoTi7PHHwwV/Ac60XjWGH8e4A8Ojb3R80rzS1EFqPR9V+TualzC/TS3c64r7q58teBBPF1S41J6SZBVQQ8ZidlTpTBMmgamffRp9kTlKxyxNa+daFtfiyFx+L1mlGVaKDVg+WYY+NPcTpuEuHEBbPCntPg5d/WvHOsPuxCUdsnwDudjdzND7mZOtBBgrdX67AE+MgWzBYjwf0atvWr02cuuNnxUXyKwRCPzed7QGb3CK9bHQr7R/7S8ATykk+kPUZld3hhvThZ0CbCmWQ4ThaHcNHA13loec1KYCcNCOhbfRT903v2vgrJXIao8jBIDdHBI1Pa5UqLsvkcVgGHyVqos25YEKNoTO3xCit++QulQV2D92B+WTDFl1pU19eGYaLB5GVeXfu2ESBTfMILVEKUTduShhPcfnvNUzp7Cgc+ci+0CNqzKMe4v6rsGXzC+Ppt2u7AT3S4UuJVC0tEbW3eo0lxF0BYvXRhQwpXeDMNE6p7cOwrE7xze3+FgRlRi1rHQ74AX+q3KIyCFQWD4HmXi3XNg+QYvucVGck7qj+mHyznWU8Pzk=
install: npm install
script:
- npm test
deploy:
  provider: heroku
  app: still-forest-14776
  api_key:
    secure: oKcK8QzqHTjeHIDwMovYvEwYQ4T0xYARlAQE57+VWbuwIC04xhpgnNHsxu+1gFg59tKzBmUZ+70pYjSrb7+H4F9qP/PYrYZLXwub1+1WmSo+b34HpY7O1oKcyprmYZJHj2R2MhOHOU2aAknFrtLPURQ2g1nVxvdbiMvSVhQ5TTiLbFxPQ5apJhlCFDi5nt1XEpDQ6sU7K1RXpO3IQ68hKgmQ3O8EZflPlzZRHUkQKLlmgFj9WjVQ4lgofgTamvyoqbycyvvuOt+H6NPiKTeS0IbqTz6BmWQOEiX9nYr4VQZV4iz90HD5yTzNHiL8OMywA8H7qd4b4KQ3vNMuummkP1lhPzxIgsBgaw55hrvUOq262BKHRP0ycrmryxS5NucyVgQ43seMT3ZzV/f3JjKUrZ92915U6eAOmyzUcot/3WW6JDx8asK18U758b8/H8TJgzOfMZjNB5JDlu2ZSQ9afYWRuSwJMTppX+HrqJlSR3d7lNFZjcPEO35jHve+OeN2q1Y4DBe9Q4SK3TGkA5ypG/edmfrDpg6KFoLiKC8OUWMcXugRTVymHVTxejt0kUx7m4Wpah23y+/s6QbFZryRcgj6PKe5OUEdeO85Ym9D7Gt330V7HgM+mDqKAvGbH+yvkuWcvUmnnqqxZBCo3gWmLuWgoPt34RbBHDUrA+R5FNo=
